---
- name: Actualizar Windows
  hosts: aws_win1
 
  tasks:
 
    - name: Instalar actualizaciones
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes

- name: Crear usuario Ansible
  hosts: aws_win1
 
  tasks:
 
    - name: Crear usuario
      win_user:
        name: ansible
        password: "PasswordTemporal123!"
        state: present
 
    - name: Agregar a administradores
      win_group_membership:
        name: Administrators
        members:
          - ansible
        state: present

- name: Generar reporte Windows
  hosts: aws_win1
  tasks:
    - name: Obtener información
      win_shell: |
        Get-ComputerInfo |
        Select CsName,
               WindowsVersion,
               OsName,
               TotalPhysicalMemory
      register: reporte
    - name: Guardar reporte
      win_copy:
        content: "{{ reporte.stdout }}"
        dest: C:\Temp\reporte.txt

- name: Revisar CPU Windows
  hosts: aws_win1
 
  tasks:
 
    - name: Obtener CPU
      win_shell: |
        (Get-Counter '\Processor(_Total)\% Processor Time').CounterSamples.CookedValue
      register: cpu
 
    - debug:
        msg: "Uso CPU actual {{ cpu.stdout }}"

- name: Verificar servicios Windows
  hosts: aws_win1
 
  vars:
    servicios:
      - Spooler
      - W32Time
      - WinRM
 
  tasks:
 
    - name: Consultar servicios
      win_service:
        name: "{{ item }}"
      register: estado
      loop: "{{ servicios }}"
 
    - name: Mostrar resultado
      debug:
        msg: "{{ item.name }} - {{ item.state }}"
      loop: "{{ estado.results }}"
