---
- name: Crear usuario Ansible
  hosts: windows
 
  tasks:
 
    - name: Crear usuario
      win_user:
        name: ansible
        password: "PasswordTemporal123!"
        state: present
 
    - name: Agregar a administradores
      win_group_membership:
        name: Administrators
        members:
          - ansible
        state: present
