---
- name: Revisar CPU Windows
  hosts: windows
 
  tasks:
 
    - name: Obtener CPU
      win_shell: |
        (Get-Counter '\Processor(_Total)\% Processor Time').CounterSamples.CookedValue
      register: cpu
 
    - debug:
        msg: "Uso CPU actual {{ cpu.stdout }}"
