---
- name: Validar espacio en disco Linux
  hosts: aws_rhel9
  become: yes
  vars:
    umbral_uso: 80
  tasks:
    - name: Obtener uso de disco
      shell: df -h / | tail -1 | awk '{print $5}' | sed 's/%//'
      register: disk_usage
      changed_when: false
    - name: Mostrar resultado
      debug:
        msg: "Uso actual del disco: {{ disk_usage.stdout }}%"
    - name: Fallar si supera el umbral
      fail:
        msg: "Disco crítico. Uso actual {{ disk_usage.stdout }}%"
      when: disk_usage.stdout | int > umbral_uso

- name: Verificar servicios Linux
  hosts: aws_rhel9
  become: yes
  vars:
    servicios:
      - sshd
      - chronyd
      - rsyslog
  tasks:
    - name: Validar servicios
      systemd:
        name: "{{ item }}"
      register: resultado
      loop: "{{ servicios }}"
    - name: Mostrar estado
      debug:
        msg: "{{ item.item }} -> {{ item.status.ActiveState }}"
      loop: "{{ resultado.results }}"

- name: Generar reporte Linux
  hosts: linux
  gather_facts: yes
 
  tasks:
 
    - name: Generar reporte
      copy:
        dest: "/tmp/reporte_{{ inventory_hostname }}.txt"
        content: |
          Hostname: {{ ansible_hostname }}
          IP: {{ ansible_default_ipv4.address }}
          Sistema: {{ ansible_distribution }}
          Version: {{ ansible_distribution_version }}
          CPU: {{ ansible_processor_vcpus }}
          RAM: {{ ansible_memtotal_mb }} MB
